on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig build
      - uses: actions/upload-artifact@v4
        with: 
          name: wasm
          path: zig-out/bin/zig-pdk-template.wasm
      
        
